In [1]:
import pandas as pd

In [18]:
df = pd.read_csv("../data/BG_IBD11102016no.csv")

In [19]:
#da = df.T

In [20]:
df.head()

,C1558705__gene_97812,C1783852__gene_117248,C2042904__gene_162511,C2440548__gene_205297,C2795872__gene_262504,C2932453__gene_110125,C3794360__gene_319820,C694214__gene_39946,C7532967__gene_57868,C8117886__gene_74963,...,gi|982522489|gb|KWR55041.1|,gi|12802353|gb|AAK07837.1|AF305888_4,gi|298266464|gb|EFI08122.1|,gi|34581787|gb|AAQ76045.1|,gi|292630908|sp|P0CE45.1|UIDB2_ECOLI,gi|1002418933|gb|KXT43298.1|,gi|1015445533|gb|AMV27317.1|,gi|147829464|emb|CAN00377.1|,gi|1002424101|gb|KXT48135.1|,gi|37200400|dbj|BAC96227.1|
0,0,0,0,0,1,1,0,2,0,0,...,9,1,2,2,1,2,2,5,8,3
1,1,0,0,0,0,0,0,0,0,1,...,1,2,3,2,4,3,3,2,3,8
2,1,0,0,0,1,0,0,0,0,0,...,3,5,6,3,1,1,4,4,7,6
3,1,0,0,0,0,0,0,1,0,0,...,3,1,3,3,5,4,7,5,10,7
4,0,0,0,1,0,0,0,0,0,0,...,0,6,0,5,5,1,1,4,1,5

In [22]:
#df.div(df.sum(axis=1), axis=0)
da = df.div(df.sum(axis=1), axis=0)

In [23]:
da.head()

,C1558705__gene_97812,C1783852__gene_117248,C2042904__gene_162511,C2440548__gene_205297,C2795872__gene_262504,C2932453__gene_110125,C3794360__gene_319820,C694214__gene_39946,C7532967__gene_57868,C8117886__gene_74963,...,gi|982522489|gb|KWR55041.1|,gi|12802353|gb|AAK07837.1|AF305888_4,gi|298266464|gb|EFI08122.1|,gi|34581787|gb|AAQ76045.1|,gi|292630908|sp|P0CE45.1|UIDB2_ECOLI,gi|1002418933|gb|KXT43298.1|,gi|1015445533|gb|AMV27317.1|,gi|147829464|emb|CAN00377.1|,gi|1002424101|gb|KXT48135.1|,gi|37200400|dbj|BAC96227.1|
0,0.000000,0.0,0.0,0.000000,0.009709,0.009709,0.0,0.019417,0.0,0.000000,...,0.087379,0.009709,0.019417,0.019417,0.009709,0.019417,0.019417,0.048544,0.077670,0.029126
1,0.011494,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.011494,...,0.011494,0.022989,0.034483,0.022989,0.045977,0.034483,0.034483,0.022989,0.034483,0.091954
2,0.007407,0.0,0.0,0.000000,0.007407,0.000000,0.0,0.000000,0.0,0.000000,...,0.022222,0.037037,0.044444,0.022222,0.007407,0.007407,0.029630,0.029630,0.051852,0.044444
3,0.008130,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.008130,0.0,0.000000,...,0.024390,0.008130,0.024390,0.024390,0.040650,0.032520,0.056911,0.040650,0.081301,0.056911
4,0.000000,0.0,0.0,0.014925,0.000000,0.000000,0.0,0.000000,0.0,0.000000,...,0.000000,0.089552,0.000000,0.074627,0.074627,0.014925,0.014925,0.059701,0.014925,0.074627

In [24]:
BG = da.T

In [25]:
BG.head()

,0,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,49,50,51
C1558705__gene_97812,0.000000,0.011494,0.007407,0.00813,0.000000,0.000000,0.000000,0.00000,0.012346,0.0,...,0.0,0.000000,0.013514,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0
C1783852__gene_117248,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.01087,0.000000,0.0,...,0.0,0.017544,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0
C2042904__gene_162511,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.010638,0.00000,0.000000,0.0,...,0.0,0.000000,0.013514,0.000000,0.000000,0.0,0.0,0.020408,0.0,0.0
C2440548__gene_205297,0.000000,0.000000,0.000000,0.00000,0.014925,0.014085,0.010638,0.00000,0.000000,0.0,...,0.0,0.000000,0.013514,0.011236,0.000000,0.0,0.0,0.000000,0.0,0.0
C2795872__gene_262504,0.009709,0.000000,0.007407,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.011905,0.0,0.0,0.020408,0.0,0.0

In [26]:
BG.to_csv("../data/BG_IBDnov11.csv")